version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - "database"

  database:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blog
    volumes:
      - "sql_data:/var/lib/mysql"
      - "/tmp:/var/lib/tmp"

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    links:
      - "database"

volumes:
  sql_data:
