version: '3'
services:
  database:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - sql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blog
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    links:
      - database

volumes:
  sql_data:
